Add link phone and .PHONY makefile targets.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,11 +3,26 @@
 set -e
 
 # Init basic profile.
-profile="${CONF:-${HOME}/conf/profile}"
+CONF="${CONF:-${HOME}/conf}"
+
+readonly branch="${CONF_BRANCH:-master}"
+readonly repo="https://github.com/shawnohare/conf.git"
+
+if [ ! -d "${CONF}" ]; then
+  echo "Cloning ${repo}"
+  git clone -b "${branch} "--recursive "${repo}" "${CONF}"
+fi
+
+if [ ! -d "${CONF}" ]; then
+  >&2 echo "Error: Could not clone config repo."
+  exit 1
+fi
+
+cd "${CONF}"
+# git checkout "${branch}"
 source profile/.env
 source profile/.profile
 
-echo "Making dirs."
 mkdir -p "${USER_BIN_HOME}"
 mkdir -p "${USER_CONFIG_HOME}"
 mkdir -p "${USER_CACHE_HOME}"
@@ -17,8 +32,7 @@ mkdir -p "${USER_SRC_HOME}"
 mkdir -p "${USER_TMP_HOME}"
 mkdir -p "${USER_VAR_HOME}"
 
-echo "Backing up profiles."
-for file in .profile .bash_profile .bashrc .zshenv .zshrc; do
+for file in .env .profile .bash_profile .bashrc .zshenv .zshrc; do
   original="${HOME}/${file}"
   backup="${original}.backup"
   [ -L "${original}" ] && continue
@@ -27,10 +41,12 @@ for file in .profile .bash_profile .bashrc .zshenv .zshrc; do
     echo "It appears some profile backups have already been created. Exiting"
     exit 1
   elif [ -f "${original}" ]; then
-    echo "Backing up ${original}"
+    echo "Backing up ${original} -> ${backup}"
     mv "${original}" "${backup}"
   fi
 done
+
+make link
 
 # NOTE:
 # Should have 3-stage for bootstrapping.
@@ -46,6 +62,5 @@ done
 # 4. Install packages: upkg or a series of commands?
 
 # Likely an abuse of make (to call it during the config part)
-make link
-
+# make link
 
